### ISSUE TITLE
Cannot load system in V10.303

### ISSUE THREAD

**Issue by Angor-de-Redjak** [razage/fabula-ultima-unofficial#51]
Hi there!

I have a little trouble here.
The manifest say the system is compatible with Foundry V10.291, but it cannot be installed with this version of Foundry.
It says:
```
[System.packs]: Model Validation Errors
Model Validation Errors
[]: may not be a blank string
```
or "Unable to load valid manifest data"

Is it still supposed to be compatible with V10?
Thanks for your answer!

**Comment by razage** [comment]
I started development on that version. I assumed that the only thing that wouldn't work would be the compendiums. It seems that might not be the case. I will most likely change the config to specify 11+. Sorry for the inconvenience.

**Comment by razage** [comment]
I have decided to focus on 11+ functionality. When Foundry 12 comes out, I will assess if backwards compatibility for 11 is feasible. If so, I will maintain that going forward. The major change from 10 to 11 is data related, so it's kind of a messy update and difficult to bridge.

This has been addressed by updating the system file to suggest 11+ for compatibility in c76127a.
