### ISSUE TITLE
First page on Items

### ISSUE THREAD

**Issue by NoxStripes** [razage/fabula-ultima-unofficial#56]
Hey this is really just a pet peeve on my end, but whenever I open an Item like a Class skill, it instantly dumps me on the general page. Having the option to instead start on the Description Page would be nice.

Like I said, super minor

**Comment by razage** [comment]
I see what you're talking about. I think that makes sense for some item types and not for others. Things like spells, skills, and arcana it would make more sense to start on the description page. Weapons and armor it doesn't matter as much. I will look into this and see how easy it would be to change.

**Comment by razage** [comment]
It was not hard to change. It also doesn't impact any of the item types I was worried about, since weapons/armor don't have a description page. Added in 9a33e49
