### ISSUE TITLE
Font Color not changing to black?

### ISSUE THREAD

**Issue by RevenantBob** [razage/fabula-ultima-unofficial#57]
I tried to set the font color to black #000000 and relaunch. The background turned white as expected but font stayed white too so I can't read anything.

**Comment by razage** [comment]
I see what you mean. I'll have to investigate this more.

**Comment by razage** [comment]
I've fixed this in commit 2a81cf5. You may have to clear your cache after you update (Shift + F5 in your browser).

The fix isn't great, but the implementation of this feature was bad to begin with. This should ideally be addressed by just having a couple of "themes" for users to choose from. But that won't be soon, so here's a bandaid.
