### ISSUE TITLE
Some missing translations

### ISSUE THREAD

**Issue by Zakarik** [razage/fabula-ultima-unofficial#60]
Hello !

I'm about to start using your system, which I discovered by chance. I'm a French speaker, so I've started looking into translating the system. I'm also a Foundry system developer, so I've noticed a few things that are easy to fix.

Firstly, there's no built-in translation for these headers (just add the i18n code to translate them):
![Capture1](https://github.com/razage/fabula-ultima-unofficial/assets/8583530/572637be-ee8d-4692-bde1-f68b6ee5866d)

Then I noticed that a few other translations were missing.
![image](https://github.com/razage/fabula-ultima-unofficial/assets/8583530/d883f9b6-52ab-4fb2-88f0-dab36a62a4b8)

When you click on "Create Actor" or "Create Item", the drop-down list I've highlighted in the image can be translated. Basically, it just takes the name assigned in the template.json file.

Except that it's modifiable, it can be translated into the json file of the corresponding language, but you need to know which path is used. This allows you to capitalize the name, or to give it a more complete name than what appears in the template file.

So the translation paths are simple:
In V11, for actors, it's :
"TYPES.Actor.player".

player is the name in the template.json file.

For items, it's the same:
"TYPES.Item.weapon"

In V10, it's a little different (I haven't checked whether your system is V10 compatible... Anyway, I'll give it to you just in case).
"ACTOR.TypePlayer"
and
"ITEM.TypeWeapon

Big differences: "Type" is added in front of the name in the JSON template, and the name is capitalized. It's possible to put both in a translation file, to be both V10 and V11 compatible.

Here's an image of the "work in progress" translation file I made for your system, to show you a complete example.

![image](https://github.com/razage/fabula-ultima-unofficial/assets/8583530/3ea96467-12d3-470b-b38a-cc5f7c02d0b9)

**Comment by Zakarik** [comment]
Another things, for the status effects.

You can give a translation path in the label (and also the description - although I don't know what the description is used for, but never mind).

For example:
![image](https://github.com/razage/fabula-ultima-unofficial/assets/8583530/f77e979d-4468-4ba7-be58-3b11c368199c)

To make things easier for you, as I've done it at home (for my own use), I'm attaching the statusConditions.js file.

It's up to you whether you want to use it as is and just add the definitions to your translation file.

If you could add my translation file to the system, I'd be grateful. Don't forget to add it to the system.json file too.
[translations.zip](https://github.com/razage/fabula-ultima-unofficial/files/14284075/translations.zip)

It's the french translation.

**Comment by razage** [comment]
Hey, thanks for pointing that out. I wasn't sure how to handle those elements with localization, which is why I left them out. I'll try to get that in soon. I'd be grateful for any translations you or anyone else has to offer; though I can't verify their accuracy since I only speak English.

As for the descriptions for status effects, I don't think they appear anywhere super visible. I have a mod that adds status effect icons in a corner of the screen, and that text displays when you hover over the icon.

**Comment by razage** [comment]
The description field doesn't seem to work the same way. That's probably related to the mod I'm using to show that. So you can safely ignore translating those for now.

**Comment by razage** [comment]
I've done the changes mentioned and add your translation file in commit 004c89a. Thanks for taking the time to translate all of that...I know the lang file is a bit of a mess. It would require a lot of work to go back and fix it, and I just can't commit that time right now.

If you notice any other areas that can be translated, please let me know and I'll try to get that done in the future as well.
