### ISSUE TITLE
Unable to install system

### ISSUE THREAD

**Issue by Ashgar225** [razage/fabula-ultima-unofficial#62]
It seems that this system does not want to be installed on my foundry server. I'm on Version 10 Stable (Build 312), and on trying to use https://raw.githubusercontent.com/razage/fabula-ultima-unofficial/master/system.json as a manifest URL I get the following error:

```
Error: Unable to load valid system manifest data from "https://raw.githubusercontent.com/razage/fabula-ultima-unofficial/master/system.json"
System Model Validation Errors
[System.packs]: Model Validation Errors
Model Validation Errors
[]: may not be a blank string
Model Validation Errors
[]: may not be a blank string
Model Validation Errors
[]: may not be a blank string
Model Validation Errors
[]: may not be a blank string
Model Validation Errors
[]: may not be a blank string
Model Validation Errors
[]: may not be a blank string
Model Validation Errors
[]: may not be a blank string
Model Validation Errors
[]: may not be a blank string
Model Validation Errors
[]: may not be a blank string
Model Validation Errors
[]: may not be a blank string
Model Validation Errors
[]: may not be a blank string
Model Validation Errors
[]: may not be a blank string
Model Validation Errors
[]: may not be a blank string
Model Validation Errors
[]: may not be a blank string
    at Module.installPackage (/home/foundry/foundryvtt/resources/app/dist/packages/views.mjs:1:1634)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async SetupView.handlePost (/home/foundry/foundryvtt/resources/app/dist/server/views/setup.mjs:1:1980)
error @ setup.js:292
```

**Comment by Ashgar225** [comment]
Having tried this in local, it seems to install in Foundry 11 (build 315), but the dependencies do not.

**Comment by razage** [comment]
1. This system no longer supports Foundry 10. This is due to a large change in how data is stored. I would need to rewrite all of the compendium for 10, and that doesn't seem feasible to me.
2. This system has no dependencies. I have a few modules as *recommendations*, but they are not required to run. I had assumed Foundry asks if you want to install these during installation, but maybe I'm wrong.

**Comment by Ashgar225** [comment]
Foundry presents the prerequisites of "Challenge Tracker" as required on install. This seems like it is probably a foundry bug and not specific to this system. Thank you very much for the response!
