### ISSUE TITLE
How to change colors?

### ISSUE THREAD

**Issue by VORCHUN1112** [razage/fabula-ultima-unofficial#9]
How can i change background and font colors in character sheets? I have tried setting up it in "fabulaultima\less\globals.less", but it doesnt work.

**Comment by razage** [comment]
I don't have an easy way to do this. You would have to change it in `fabulaultima\less\globals.less`, but then you'd have to compile it, using a less compiler.

**Comment by razage** [comment]
I've added _some_ ability to change color in commit 07da929 to the beta branch. You will be able to customize the bg of the sheet and the font color, but you cannot change the tabs themselves. Changing that would be fairly involved and would require sacrifices on the default style.
